- name: Install required packages
  ansible.builtin.apt:
    name:
      - python3-dnspython
      - python3-ipy
      - python3-ldap
      - sssd
      - libnss-sss
      - libpam-sss
      - libsss-sudo
      - heimdal-clients
      - ntpdate
      - sshpass
      - autofs
      - nfs-common
    update_cache: yes
