- name: copy sudoers "ansible"
  ansible.builtin.copy:
    src: files/etc/sudoers.d/w_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: copy sudoers "ucs.damantec.org"
  ansible.builtin.copy:
    src: files/etc/sudoers.d/w_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440